### ISSUE TITLE
Add the Portuguese language

### ISSUE THREAD

**Issue by hlorenzi** [r12a/app-charuse#1]
I noticed the Portuguese language is missing; are you accepting new language additions from users?

**Comment by r12a** [comment]
@hlorenzi sorry, I missed this.  I think i was still creating the data at the time of your comment, and hadn't reached P.  You should see it now at https://r12a.github.io/app-charuse/

**Comment by hlorenzi** [comment]
Hahaha, I jumped the gun there. Didn't realize you were still adding data. I just love Unicode. Do you have a Discord for discussing stuff or something?

**Comment by r12a** [comment]
Not sure what Discord is, but if you want to raise issues this is the place to do so.

**Comment by hlorenzi** [comment]
No... I just wanted to chat with you 😛

**Comment by Thanderpyae** [comment]
#1
