### ISSUE TITLE
[app-charuse]  Shilluk (shk) circumflex

### ISSUE THREAD

**Issue by r12a** [r12a/app-charuse#2]
appears to be missing from the data, see https://en.wikipedia.org/wiki/Shilluk_language

(note also combination of cirumflex and acute above, should probably map to Ấ etc)

**Comment by moyogo** [comment]
These only seem to be used in phonetic notation and not in the orthography.

**Comment by moyogo** [comment]
See for example [Cøllø (aka Shilluk) Dictionary](https://shilluk.webonary.org/browse/browse-shilluk-english/) or [Bert Remijsen, Otto Gwado Ayoker & Amy Martin, *Shilluk Lexicography With Audio Data*](https://datashare.is.ed.ac.uk/bitstream/handle/10283/3218/ShillukLexicography.pdf).

**Comment by r12a** [comment]
Finally getting to these issues. I updated Shilluk per the Wikipedia article, but i want the app to reflect the orthography rather than phonetic notation, so i didn't implement the additional characters or combinations you mentioned here. See https://github.com/r12a/app-charuse/commit/7b9b98a8ced343c0f2356595d76c12d32b5dd0a5

Closing this then. Reopen if you want to add more thoughts.
