### ISSUE TITLE
Update Kashmiri

### ISSUE THREAD

**Issue by moyogo** [r12a/app-charuse#4]
Both 0653 ARABIC MADDAH ABOVE and 06ED ARABIC SMALL LOW MEEM have been removed
from the CLDR Kashmiri locale character exemplar.

See https://unicode.org/cldr/trac/ticket/6782

**Comment by r12a** [comment]
I see changes coming in CLDR 35beta.  Once that is released, i'll make the corresponding changes.

**Comment by r12a** [comment]
Change made at https://github.com/r12a/app-charuse/commit/57237835618d4daaf27d149d55e14be159182c33

End result is removal of the following:
 ‎065A ARABIC VOWEL SIGN SMALL V ABOVE
 ‎065B ARABIC VOWEL SIGN INVERTED SMALL V ABOVE
 ‎06EA ARABIC EMPTY CENTRE LOW STOP
 ‎06ED ARABIC SMALL LOW MEEM

Reopen if additional problems for Kashmiri.
